#include "ZScript/Goldfinger/Goldfinger_Bodies.zs"
#include "ZScript/Goldfinger/Goldfinger_Heads.zs"
#include "ZScript/Goldfinger/Goldfinger_Hats.zs"
#include "ZScript/Goldfinger/Goldfinger_Guns.zs"
#include "ZScript/Goldfinger/Goldfinger_Flashes.zs"