#include "ZScript/Goldeneye/Goldeneye_Animations.zs"
#include "ZScript/Goldeneye/Goldeneye_Bodies.zs"
#include "ZScript/Goldeneye/Goldeneye_Heads.zs"
#include "ZScript/Goldeneye/Goldeneye_Hats.zs"
#include "ZScript/Goldeneye/Goldeneye_Guns.zs"