Script "WitchHoundBite" (void) CLIENTSIDE //1767
{
	int i;
	int sHoundBNum;

	FadeTo(0,0,0,1.0,0);
	SetHudSize(214,200,1);
	
	for(i = 1; i <= 5; i++){
		sHoundBNum = strparam(s:"SHOUNDB", d:i);
		SetFont(sHoundBNum);
		HudMessage(s:"A";0,500+PlayerNumber(),0,107.0,100.0,0.5);
		Delay(SHADOW_HOUND_BITE);
	}	

    HudMessage(s:"";0,500+PlayerNumber(),0,107.0,100.0,0.1);
	Delay(SHADOW_HOUND_BITE);	
	FadeTo(0,0,0,0,1.5);
	Delay(2);
}