/*======================================================================================================================
													Design Specs
													
o MAX_GAME_TYPES
	- This corresponds to the game set, like Doom or Chex
o MAX_ALTS
	- This corresponds to a game alt set, like Opposing Force
o MONSTER_SLOT
	- This corresponds to the monster slot, like Zombieman. Slots are in this order:
										0: 	Zombieman
										1: 	Shotgunguy
										2: 	Imp
										3: 	Chaingunner
										4: 	Demon
										5: 	Spectre
										6: 	Hellknight
										7: 	Baron of Hell
										8: 	Arachnotron
										9: 	Mancubus
										10: Lost Soul
										11: Pain Elemental
										12: Cacodemon
										13: Revenant
										14: Archvile
										15: Cyberdemon
										16: Spider Mastermind
										17: Wolfenstein SS
										18: Super Shotgunguy
										19: Dark Imp
										20: Blood Demon
										21: Cacolantern
										22: Abaddon
										23: Hectebus
										24: Belphegor
o MAXPERSLOT
	- This variable is the slot for a decision on the monster from the slot, like spawning a zombieman variant
			
													- Strings -
	o Monster name:
		- Name of the the monster
	o Token0-4:
		- These are inventory items that can be given to a monster for each difficulty, to alter their behavior
		
													- Stats -
	o Speed0-4:
		- These tokens work as a multiplier for monster speed. As such, you should never use numbers with no decimal
		decimal point. Please use 2.0 instead of 2. If left alone, it will have no affect.
	o Health0-4:
		- A health multiplier. Same as speed, these are multipliers. If left alone, it will have no affect.
	o Weight0-4:
		- This is a spawn chance, which functions similarly to RandomSpawner. You can use whatever numbers you want,
		to define the chance of a monster spawning. The higher the weight compared to other monsters, the more likely
		it is to spawn, and vice versa. If left alone, will be treated as 1. If set to a negative value, however,
		that means the monster will not spawn at all on that difficulty.

======================================================================================================================*/
//Monster name, 										token0, 									token1, 									token2, 								token3, 								token4						token5
int monsterSelectStr[MAX_GAME_TYPES][MAX_ALTS][MONSTER_SLOT][MAXPERSLOT][6] = 
{	
	{	//Doom
		{	//Classic	
			{
				{ "Zombieman3" }
			},
			{
				{ "Shotgunguy3" }
			},
			{
				{ "DoomImp3" }
			},
			{
				{ "Chaingunguy3" }
			},
			{
				{ "DoomDemon3" }
			},
			{
				{ "Spectre3" }
			},
			{
				{ "HellKnight3" }
			},
			{
				{ "BaronofHell3" }
			},
			{
				{ "Arachnotron3" }
			},
			{
				{ "Fatso3" }
			},
			{
				{ "LostSoul3" }
			},
			{
				{ "PainElemental3" }
			},
			{
				{ "Cacodemon3" }
			},
			{
				{ "Revenant3" }
			},
			{
				{ "Archvile3" }
			},
			{
				{ "Cyberdemon3" }
			},
			{
				{ "SpiderMastermind3" }
			},
			{
				{ "Nazi3" }
			},
			{
				{ "SuperShotgunguy2" }
			},
			{
				{ "DarkImp2" }
			},
			{
				{ "BloodDemon2" }
			},
			{
				{ "Cacolantern2" }
			},
			{
				{ "Abaddon2" }
			},
			{
				{ "Hectebus2" }
			},
			{
				{ "Belphegor2" }
			},
		},
		{	//64	
			{
				{ "Zombieman64" }
			},
			{
				{ "Shotgunguy64" }
			},
			{
				{ "DoomImp64" },
				{ "NightmareImp64" }
			},
			{
				{ "Chaingunguy64" }
			},
			{
				{ "Demon64" }
			},
			{
				{ "Spectre64" }
			},
			{
				{ "HellKnight64" }
			},
			{
				{ "BaronofHell64" }
			},
			{
				{ "Arachnotron64" }
			},
			{
				{ "Fatso64" }
			},
			{
				{ "LostSoul64" }
			},
			{
				{ "PainElemental64" }
			},
			{
				{ "Cacodemon64" }
			},
			{
				{ "Revenant64" }
			},
			{
				{ "Archvile64" }
			},
			{
				{ "Cyberdemon64" }
			},
			{
				{ "SpiderMastermind64" },
				{ "MotherDemon64" }
			},
			{
				{ "WolfensteinSSJagaur" }
			},
		},
		{	//VDR	
			{
				{ "ZombieManRandomizer" }
			},
			{
				{ "ShotgunguyRandomizer" }
			},
			{
				{ "DoomImpRandomizer" }
			},
			{
				{ "ChaingunguyRandomizer" }
			},
			{
				{ "DoomDemonRandomizer" }
			},
			{
				{ "SpectreRandomizer" }
			},
			{
				{ "HellKnightRandomizer" }
			},
			{
				{ "BaronofHell3" },
				{ "MMRandomizer_HellsFury" }, 
				{ "MMRandomizer_CyberBaron" },
				{ "MMRandomizer_BruiserDemon" },
				{ "MMRandomizer_Belphegor" },
			},
			{
				{ "Arachnotron3" }, 
				{ "MMRandomizer_ChaingunArachnotron" }, 
				{ "MMRandomizer_RailgunArachnotron" },
			},
			{
				{ "Fatso3" }, 
				{ "MMRandomizer_Cryocubus" }, 
				{ "MMRandomizer_Hectebus" },
			},
			{
				{ "LostSoulRandomizer" }
			},
			{
				{ "PainElementalRandomizer" }
			},
			{
				{ "CacodemonRandomizer" }
			},
			{
				{ "RevenantRandomizer" }
			},
			{
				{ "ArchvileRandomizer" }
			},
			{
				{ "Cyberdemon3" }, 
				{ "MMRandomizer_ArchonOfHell" }, 
				{ "MMRandomizer_Annihilator" },
			},
			{
				{ "SpiderMastermind3" }, 
				{ "MMRandomizer_ArachnorbQueen" }, 
				{ "MMRandomizer_Demolisher" },
			},
			{
				{ "Nazi3" }
			},
		},
	},
	{	//Chex
		{ 
			{
				{ "FlemoidusCommonus3" }
			},
			{
				{ "FlemoidusBipedicus3" }
			},
			{
				{ "NewArmoredFlemoidusBipedicus" }
			},
			{
				{ "NewArmoredFlemoidusBipedicus" }
			},
			{
				{ "NewFlemoidusStridicus" }
			},
			{
				{ "NewFlemoidusCycloptisCommonus" }, 
				{ "NewLarva" },
			},
			{
				{ "NewQuadrumpus" }
			},
			{
				{ "OldFlemoidusMaximusDoom" }
			},
			{
				{ "NewQuadrumpus" }
			},
			{
				{ "NewQuadrumpus" }
			},
			{
				{ "FlemMine2" }, 
				{ "NewFlemoidusGyro" },
			},
			{
				{ "SuperCycloptis2" }
			},
			{
				{ "SuperCycloptis2" }
			},
			{
				{ "NewQuadrumpus" }
			},
			{
				{ "NewSnotfolus" }
			},
			{
				{ "FlembominationNew" }
			},
			{
				{ "YellowArmoredFlemoid" }
			},
		}
	},
	{	//Heretic
		{ 
			{
				{ "Mummy3Doom" }
			},
			{
				{ "MummyLeader3Doom" }
			},
			{
				{ "HereticImpLeader3" }
			},
			{
				{ "Knight3Doom" }
			},
			{
				{ "Clink3Doom" }
			},
			{
				{ "KnightGhost3Doom" }, 
				{ "MummyGhost3Doom" },
				{ "MummyLeaderGhost3Doom" },
			},
			{
				{ "Beast3Doom" }
			},
			{
				{ "Beast3Doom" }
			},
			{
				{ "Snake3Doom" }
			},
			{
				{ "Beast3Doom" }
			},
			{
				{ "HereticImp3" }
			},
			{
				{ "Wizard3Doom" }, 
			},
			{
				{ "Wizard3Doom" }
			},
			{
				{ "Snake3Doom" }
			},
			{
				{ "IronLich3Doom" }
			},
			{
				{ "Minotaur3" }
			},
			{
				{ "Sorcerer5" }
			},
			{
				{ "CyCloneGrunt" }
			},
		}
	},
	{ //Wolf 3D
		{ 
			{
				{ "WolfGuard" }
			},
			{
				{ "WolfOfficer" }
			},
			{
				{ "WolfOfficer" }
			},
			{
				{ "WolfSS" }
			},
			{
				{ "WolfDog" }
			},
			{
				{ "WolfDogSpectre" }
			},
			{
				{ "WolfMutant" }
			},
			{
				{ "HansGrosseDoom" },
				{ "GretelGrosseDoom" },
			},
			{
				{ "OttoGiftmacherDoom" }
			},
			{
				{ "OttoGiftmacherDoom" }
			},
			{
				{ "WolfSpectre" }
			},
			{
				{ "FakeHitler" }, 
			},
			{
				{ "FakeHitler" }
			},
			{
				{ "WolfMutant" }
			},
			{
				{ "TransGrosseDoom" }
			},
			{
				{ "DoctorSchabbs" },
				{ "AngelofDeath" },
				{ "BarnacleWilhelm" },
				{ "UberMutant" },
				{ "BarnacleWilhelm" },
			},
			{
				{ "GeneralFettgesicht" },
				{ "WDeathKnight" },
				{ "MechaHitler" },
			},
			{
				{ "Wolf3D_RussianRedArmy" }
			},
		},
		{ 
			{
				{ "SODGuard" }
			},
			{
				{ "SODOfficer" }
			},
			{
				{ "SODOfficer" }
			},
			{
				{ "SODSS" }
			},
			{
				{ "SODDog" }
			},
			{
				{ "SODDogSpectre" }
			},
			{
				{ "SODBat" }
			},
			{
				{ "GeneralleutnantStahlkopfDoom" },
			},
			{
				{ "GerhardtVonSchreiberDoom" }
			},
			{
				{ "GerhardtVonSchreiberDoom" }
			},
			{
				{ "SODSpectre" },
				{ "SODSpectre2" }
			},
			{
				{ "FireDrone" }, 
			},
			{
				{ "FireDrone" }
			},
			{
				{ "SODBat" }
			},
			{
				{ "SubmarineWillyDoom" }
			},
			{
				{ "ProfessorQuarkblitz" },
				{ "TheAxe" },
			},
			{
				{ "Robot" },
				{ "DevilIncarnate" },
			},
			{
				{ "Wolf3D_RussianRedArmy" }
			},
		},
		{ 
			{
				{ "TotenkopfGuardSpawner" },
				{ "TotenkopfScientistSpawner" },
			},
			{
				{ "TotenkopfInfantrySpawner" }
			},
			{
				{ "TotenkopfGuardSpawner" }
			},
			{
				{ "TotenkopfSSSpawner" },
				{ "TotenkopfMutantSpawner" }
			},
			{
				{ "TotenkopfDogSpawner" }
			},
			{
				{ "TotenkopfDogSpawner" }
			},
			{
				{ "TotenkopfTrooperPanzerschreck" }
			},
			{
				{ "TotenkopfHansGrosse" }
			},
			{
				{ "TotenkopfTrooperChaingun" }
			},
			{
				{ "TotenkopfTrooperFlamethrower" }
			},
			{
				{ "TotenkopfGhost" }
			},
			{
				{ "TotenkopfMonk" }
			},
			{
				{ "TotenkopfMonk2" }
			},
			{
				{ "TotenkopfWaffenSSSpawner" }
			},
			{
				{ "TotenkopfMechanoidStormTrooper" }
			},
			{
				{ "TotenkopfSchabbsMutant" },
				{ "TotenkopfNarbengesicht" },
			},
			{
				{ "TotenkopfPanzGrosse" },
				{ "TotenkopfDeathMutant" },
			},
			{
				{ "Wolf3D_RussianRedArmy" }
			},
		}
	},
	{	//Hexen
		{ 
			{
				{ "Ettin3Doom" }
			},
			{
				{ "Ettin3Doom" }
			},
			{
				{ "FireDemon3Doom" },
				{ "Ettin3Doom" }
			},
			{
				{ "FireDemon3Doom" }
			},
			{
				{ "Centaur3Doom" }
			},
			{
				{ "CentaurLeader3Doom" }, 
			},
			{
				{ "Demon1CDoom" }
			},
			{
				{ "Demon2CDoom" }
			},
			{
				{ "Dragon3Doom" }
			},
			{
				{ "IceGuy3Doom" }, 
			},
			{
				{ "FireDemon3Doom" }
			},
			{
				{ "Wraith3Doom" },
				{ "Bishop3Doom" },
			},
			{
				{ "Wraith3Doom" },
				{ "Bishop3Doom" },
			},
			{
				{ "IceGuy3Doom" }
			},
			{
				{ "ClericBoss3Doom" },
				{ "FighterBoss3Doom" },
				{ "MageBoss3Doom" },
			},
			{
				{ "Heresiarch3Doom" }
			},
			{
				{ "Korax3Doom" }
			},
			{
				{ "Pig3" }
			},
		}
	},
	{	//Duke 3D
		{ 
			{
				{ "AssaultTrooper" }
			},
			{
				{ "PigCop" },
				{ "ZombiePigCop" },
				{ "MagnumPig" },
			},
			{
				{ "AssaultCaptain" },
				{ "AssaultGeneral" },
				{ "AssaultTrooper" },
			},
			{
				{ "AssaultEnforcer" },
				{ "PiginaDress" }
			},
			{
				{ "ProtozoidEgg" }
			},
			{
				{ "ProtozoidEgg" },
			},
			{
				{ "AssaultCommander" },
			},
			{
				{ "MiniBattlelordDoom" }
			},
			{
				{ "PigCopTank" }
			},
			{
				{ "ScorpionTank" }, 
			},
			{
				{ "SentryDrone" }
			},
			{
				{ "ReconPatrolVehicle" },
			},
			{
				{ "Octabrain" },
				{ "SharkDrone" },
			},
			{
				{ "AssaultCommander" }
			},
			{
				{ "ProtectorDroneDoom" },
			},
			{
				{ "BattlelordDoom" },
				{ "OverlordDoom" },
			},
			{
				{ "CycloidEmperorDoom" },
				{ "AlienQueenDoom" },
				{ "CyberKeef" },
			},
			{
				{ "AssaultTrooper" }
			},
		},
		{ 
			{
				{ "BeachTrooper" },
			},
			{
				{ "BeachPig" },
				{ "MagnumPig" },
			},
			{
				{ "BeachCaptain" },
				{ "BeachGeneral" },
				{ "BeachTrooper" },
			},
			{
				{ "SeaMonster" },
			},
			{
				{ "ProtozoidEgg" }
			},
			{
				{ "ProtozoidEgg" },
			},
			{
				{ "BeachCommander" },
			},
			{
				{ "MiniBattlelordDoom" }
			},
			{
				{ "PigCopTank" }
			},
			{
				{ "ScorpionTank" }, 
			},
			{
				{ "SentryDrone" },
				{ "Seagull" },
			},
			{
				{ "ReconPatrolVehicle" },
			},
			{
				{ "BeachOctabrain" },
				{ "SharkDrone" },
			},
			{
				{ "BeachCommander" }
			},
			{
				{ "ProtectorDroneDoom" },
			},
			{
				{ "BattlelordDoom" },
				{ "OverlordDoom" },
			},
			{
				{ "BeachCycloidEmperorDoom" },
				{ "AlienQueenDoom" },
				{ "CyberKeef" },
			},
			{
				{ "BeachTrooper" }
			},
		}
	},
	{	//Marathon
		{ 
			{
				{ "FighterMinor" },
				{ "ProjectileFighterMinor" },
				{ "M1FighterMinor" },
				{ "M1ProjectileFighterMinor" },
				{ "MSimulacrum" },
				{ "M2Simulacrum" }
			},
			{
				{ "ProjectileFighterMinor" },
				{ "M1ProjectileFighterMinor" },
				{ "MSimulacrum" },
				{ "M2Simulacrum" },
				{ "ProjectileFighterMajor" },
				{ "M1ProjectileFighterMajor" }
			},
			{
				{ "SewageFlickta" },
				{ "LavaFlickta" },
				{ "ProjectileFighterMajor" },				
			},
			{
				{ "TrooperMinor" },
				{ "M1TrooperMinor" },
				{ "TrooperMajor" }, 
				{ "M1TrooperMajor" }
			},
			{
				{ "FighterMajor" },
				{ "WaterFlickta" },
				{ "DrinniolMinor" },
				{ "DrinniolMajor" },
				{ "SuperFighter" }
			},
			{
				{ "WaterFlickta" },
				{ "MLooker" },
				{ "MLooker2" },				
				{ "DrinniolMinor" },
				{ "DrinniolMajor" },
				{ "SuperFighter" }
			},
			{
				{ "HunterMinor" },
				{ "M1HunterMinor" }
			},
			{
				{ "HunterMajor" },
				{ "M1HunterMajor" }	,
				{ "MotherofAllHunters" }
			},
			{
				{ "FlameCyborgMinor" }, 
				{ "FlameCyborgMajor" }, 
//				{ "MotherofAllCyborgs" }
			},			
			{
				{ "CyborgMinor" },
				{ "CyborgMajor" },
				{ "MotherofAllCyborgs" }
			},
			{
				{ "DroneMinor" },
				{ "MWasp" },
				{ "M2Tick" },
				{ "DroneMajor" },
				{ "MWasp2" },
				{ "M2TickBomb" }
			},
			{
				{ "SphtMajor" },
				{ "M1SphtMajor" },
				{ "SphtKrMinor" },
				{ "SphtKrMajor" },
				{ "MADD2" },
				{ "M2EliteSpht" }
			},
			{
				{ "SphtMinor" },
				{ "MADD1" },
				{ "M1SphtMinor" }
			},
			{
				{ "M1EnforcerMinor" },
				{ "M2EnforcerMinor" },
				{ "M1EnforcerMajor" },
				{ "M2EnforcerMajor" }
			},
			{
				{ "M2EliteEnforcerMinor" },
				{ "M2EliteEnforcerMajor" },
				{ "SuperTrooper" },
			},
			{
				{ "JuggernautMajor" },
				{ "JuggernautMinor" }
			},
			{
				{ "M1Juggernaut" }
			},
			{
				{ "Marathon_Headless" }
			},
		}
	},	
	{ //Quake
		{
			{
				{ "QGrunt" },
				{ "RottWeiler" }
			},	
			{
				{ "QEnforcer" }
			},
			{
				{ "QZombie" }
			},
			{
				{ "QCentroid" }
			},
			{
				{ "QKnight" },
				{ "QKStatue1" },
				{ "QGremlin" }
			},
			{
				{ "QPhantomSwordsman" },
				{ "Quake_Spawn" },
				{ "Quake_HellSpawn" },
				{ "Quake_HellSpawn_2" }
			},	
			{
				{ "QFiend" },
				{ "QGuardian" }
			},
			{
				{ "QGuardian2" },
				{ "QGuardian3" },
				{ "QGuardian4" },
				{ "QMummy" }
			},	
			{
				{ "Vore" }
			},	
			{
				{ "QHKnight" },
				{ "QKStatue2" }
			},
			{
				{ "QSpikeMine" }
			},
			{
				{ "QWrath" }
			},
			{
				{ "QScrag" }
			},
			{
				{ "QOgre" },
				{ "QMultiOgre" }
			},
			{
				{ "Shambler" },
			},	
			{
				{ "Pterodactylus" },
				{ "QArmagon" },
			},
			{
				{ "Shub-Niggurath" },
				{ "QOverlord" },
			},
			{
				{ "Zombieman3" },
			}
		}
	},	
	{ // RoTT
		{
			{
				{ "LowGuard" }
			},
			{
				{ "LightningGuard", 					"", 					"", 					"", 					"", 					"LightningGuardCrezzyMan" },
				{ "HeavyGuard", 						"", 					"", 					"", 					"", 					"LightningGuardCrezzyMan" }
			},
			{
				{ "LowGuard" }
			},
			{
				{ "HighGuard" }
			},
			{
				{ "MonkDrain_Weak" }
			},
			{
				{ "MonkDrain_Weak" }
			},
			{
				{ "RobotGuard" }
			},
			{
				{ "GeneralDarian" } // traded for AV slot with Enforcer
			},
			{
				{ "MonkDeathFire" } // now an Arachno replacement so both DS enemies aren't the same thing
			},
			{
				{ "Ballistikraft" }
			},
			{
				{ "ExplosiveDiskJr" }
			},
			{
				{ "CopterPatrol2" }
			},
			{
				{ "CopterPatrol" }
			},	
			{
				{ "OverPatrol" },
				{ "StrikeTeam" } // very low health for Rev replacements, but they're very annoying and can be a serious threat in groups
			},
			{
				{ "TriadEnforcer" }
			},
			{
				{ "TomHall" },
				{ "NME" }
			},	
			{
				{ "SnakeTom" },
				{ "SebastianKrist" }
			},
			{
				{ "WolfGaurd" }
			},
		}
	},	
	{ //Blake Stone
		{
			{
				{ "Informant" },
				{ "SectorGuard" },
				{ "SectorPatrol" }
			},
			{
				{ "SectorGuard" },
				{ "SectorPatrol" },
				{ "MutatedGuard" }
			},
			{
				{ "MutantBrown" }
			},
			{	
				{ "BlakeSentinel" },
				{ "TechWarrior" }
			},
			{
				{ "MutantGreen" }
			},
			{
				{ "WaterAlien" } //not a suitable AV replacement
			},	
			{
				{ "ExpMutantBrown" },
				{ "GeneticGuard" },
				{ "PodAlien" }
			},
			{
				{ "ExpMutantBlue" },
				{ "CyborgWarrior" }
			},	
			{
				{ "SpiderMutant" }
			},
			{
				{ "AcidDragon" },
				{ "BioMech" }
			},
			{
				{ "PerScanDrone" },
				{ "PlasmaSphere" }
			},
			{
				{ "PerGunnerDrone" }
			},
			{
				{ "PerGunnerDrone" }
			},
			{
				{ "ReptilianWarrior" },
				{ "MechSentinel" },
				{ "StarTrooper" },
				{ "AlienProtector" }
			},
			{
				{ "BreatherBeast" },
				{ "PlasmaAlien" }
			},
			{
				{ "GiantStalker" },
				{ "CrawlerBeast" },
				{ "SpectorDemon" },
				{ "ArmoredStalker" }
			},
			{
				{ "GoldFire"}
			},
			{
				{ "Informant" },
			}	
		}
	},	
	
	{ //Blood
		{
			{
				{ "Cultist",								"",						"",						"",						"CultistWellDone",		"CultistExtraCrispy"},
			},
			{
				{ "Cultist",								"",						"",						"",						"CultistWellDone",		"CultistExtraCrispy"},
			},
			{
				{ "BloodAcolyte",						"",						"",						"",						"CultistWellDone",		"CultistExtraCrispy"},
			},
			{
				{ "Fanatic",								"",						"",						"",						"CultistWellDone",		"CultistExtraCrispy"},
			},	
			{
				{ "AxeZombie" },
				{ "GillBeast" }
			},
			{
				{ "ChokingHand" }
			},
			{
				{ "Butcher" }
			},
			{
				{ "BloodBeast" }
			},
			{
				{ "Zealot",							"",						"",						"",						"CultistWellDone",		"CultistExtraCrispy"}
			},
			{
				{ "MotherSpider" }
			},
			{
				{ "BloodBat" }
			},
			{
				{ "BloodPhantasm" }
			},
			{
				{ "BloodGargoyle" }
			},	
			{
				{ "HellHound" } // heck hound is rev now
			},
			{
				{ "BloodPriest",							"",						"",						"",						"CultistWellDone",		"CultistExtraCrispy"}
			},
			{
				{ "Cerberus" },
				{ "Cheogh" }
			},
			{
				{ "Tchernobog" }
			},
			{
				{ "Cultist", 							"",						"",						"",						"CultistWellDone",		"CultistExtraCrispy"}
			}	
		}
	},
	{	// Strife
		{
			{
				{ "StrifeAcolyte" },
				{ "StrifeAcolyte2" }
			},
			{
				{ "StrifeAcolyte3" },
				{ "StrifeAcolyte4" }
			},
			{
				{ "StrifeCultist" }
			},
			{
				{ "StrifeAcolyte5" },
				{ "StrifeAcolyte6" }
			},
			{
				{ "StrifeStalker" }
			},
			{
				{ "ShadowStalker" }
			},
			{
				{ "StrifeTemplar" }
			},
			{
				{ "NewStrifeBishop" } 
			},
			{
				{ "NewAlienSpectre2" },
			},
			{
				{ "StrifeCrusader" },
			},
			{
				{ "StrifeSentinel" },
			},
			{
				{ "Programmer3" },
				{ "NewAlienSpectre1" }
			},
			{
				{ "Recycler" },
			},
			{
				{ "StrifeReaver" },
			},
			{
				{ "NewAlienSpectre3" }, 
				{ "NewAlienSpectre4" }
			},
			{
				{ "NewAlienSpectre5" },
				{ "StrifeInquisitor" }
			},
			{
				{ "StrifeEntity" }
			},
			{
				{ "StrifeAcolyte7" },
				{ "StrifeAcolyte8" }
			}
		}
	},	
	{ // Eradicator
		{
			{
				{ "LSD" }
			},
			{
				{ "EradArcher" }
			},
			{
				{ "HSD" },
			},
			{
				{ "Skeeving" }
			},
			{
				{ "BoonBitter" }
			},
			{
				{ "BoonBitter" }
			},			
			{
				{ "HSD2" }
			},
			{
				{ "RotoDroid" },
			},
			{
				{ "LSD2" },
			},
			{
				{ "RepairDroid" },
			}, 
			{	
				{ "PatrolEyeSpawner" },
				{ "MiniBio" },
				{ "GunTurret1" }				
			},
			{
				{ "MiniRepairDroid" },
			},
			{
				{ "EradMindBreaker" },
				{ "MiniMech" }
			},
			{
				{ "LSD2" }
			},
			{
				{ "RotoDroid" }
			},
			{
				{ "RSA" },
				{ "Skaal" }
			},
			{
				{ "GorBoss" }
			},	
			{
				{ "EradArcher" },
			}
		}
	},	
	{
		{
			{
				{ "AnimatedProbe" }
			},
			{
				{ "Rodex" }
			},
			{
				{ "Bandor" }
			},
			{
				{ "Eitak" }
			},
			{
				{ "Semaj" }
			},
			{
				{ "Semaj" }
			},
			{
				{ "Otrebor" }
			},
			{
				{ "EniramBoss" }
			},
			{
				{ "Nerraw" }
			},
			{
				{ "Ttocs" }
			},
			{
				{ "SectorProbe" }
			},
			{ 
				{ "C7AlienTeleport" }
			},
			{
				{ "Ailoprobe" }
			},
			{
				{ "Tenaj" },
				{ "Eniram" }
			},	
			{
				{ "C7MWarrior" }
			},
			{
				{ "Tymok" },
				{ "Solrac" }
			},
			{
				{ "Tebazile" }
			},
			{
				{ "OBCTerrorist" }
			}
		}
	},	
};
//				speed0		health0		weight0		speed1		health1		weight1		speed2		health2		weight2		speed3		health3		weight3		speed4		health4		weight4
int monsterSelectStat[MAX_GAME_TYPES][MAX_ALTS][MONSTER_SLOT][MAXPERSLOT][MAX_ITEMS] = 
{	
	{ //Doom
		{},
		{
			{},
			{},
			{
				{0, 		0, 			4, 			0, 			0, 			3, 			0, 			0, 			2, 			0, 			0, 			1, 			0, 			0, 			-1 }, 
				{0, 		0, 			1, 			0, 			0, 			2, 			0, 			0, 			3, 			0, 			0, 			4}
			}
		},
		{
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{	
				{0, 		0, 			8, 			0, 			0, 			8, 			0, 			0, 			8, 			0, 			0, 			8, 			0, 			0, 			8 },	
				{0, 		0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5 },	
				{0, 		0, 			4, 			0, 			0, 			4, 			0, 			0, 			4, 			0, 			0, 			4, 			0, 			0, 			4 },	
				{0, 		0, 			3, 			0, 			0, 			3, 			0, 			0, 			3, 			0, 			0, 			3, 			0, 			0, 			3 },	
				{0, 		0, 			2, 			0, 			0, 			2, 			0, 			0, 			2, 			0, 			0, 			2, 			0, 			0, 			2 },	
			},
			{},
			{
				{0, 		0, 			6, 			0, 			0, 			6, 			0, 			0, 			6, 			0, 			0, 			6, 			0, 			0, 			6 },	
				{0, 		0, 			4, 			0, 			0, 			4, 			0, 			0, 			4, 			0, 			0, 			4, 			0, 			0, 			4 },	
				{0, 		0, 			2, 			0, 			0, 			2, 			0, 			0, 			2, 			0, 			0, 			2, 			0, 			0, 			2 },	
			},
		}
	},	
	{},
	{},
	{ //Wolf 3D
		{},
		{},
		{
			{},
			{},
			{},
			{
				{0, 		0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5 },	
				{0, 		0, 			3, 			0, 			0, 			3, 			0, 			0, 			3, 			0, 			0, 			3, 			0, 			0, 			3 },	
			},
		}
	},
	{ //Hexen
		{
			{},
			{},
			{
				{0, 		0, 			1, 			0, 			0, 			1, 			0, 			0, 			1, 			0, 			0, 			1, 			0, 			0, 			1 }, 
				{0, 		0, 			3, 			0, 			0, 			3, 			0, 			0, 			3, 			0, 			0, 			3, 			0, 			0, 			3 }, 
			}
		}
	},
	{ //Duke 3D
		{
			{},
			{},
			{
				{0, 		0, 			12, 		0, 			0, 			12, 		0, 			0, 			12, 		0, 			0, 			12, 		0, 			0, 			12 }, 
				{0, 		0, 			2, 			0, 			0, 			2, 			0, 			0, 			2, 			0, 			0, 			2, 			0, 			0, 			2 }, 
			},
			{
				{0, 		0, 			7, 			0, 			0, 			7, 			0, 			0, 			7, 			0, 			0, 			7, 			0, 			0, 			7 }, 
			},
			{
				{0, 		0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5 }, 
			},
			{
				{0, 		0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5 }, 
			},
			{
				{0, 		0, 			15, 		0, 			0, 			15, 		0, 			0, 			15, 		0, 			0, 			15, 		0, 			0, 			15 }, 
			},
			{},
			{
				{0, 		0, 			19, 		0, 			0, 			19, 		0, 			0, 			19, 		0, 			0, 			19, 		0, 			0, 			19 }, 
			},	
		},
		{
			{
				{0, 		0, 			14, 		0, 			0, 			14, 		0, 			0, 			14, 		0, 			0, 			14, 		0, 			0, 			14 }, 
			},
			{},
			{
				{0, 		0, 			12, 		0, 			0, 			12, 		0, 			0, 			12, 		0, 			0, 			12, 		0, 			0, 			12 }, 
				{0, 		0, 			2, 			0, 			0, 			2, 			0, 			0, 			2, 			0, 			0, 			2, 			0, 			0, 			2 }, 
			},
			{
				{0, 		0, 			7, 			0, 			0, 			7, 			0, 			0, 			7, 			0, 			0, 			7, 			0, 			0, 			7 }, 
			},
			{
				{0, 		0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5 }, 
			},
			{
				{0, 		0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5, 			0, 			0, 			5 }, 
			},
			{
				{0, 		0, 			15, 		0, 			0, 			15, 		0, 			0, 			15, 		0, 			0, 			15, 		0, 			0, 			15 }, 
			},
			{},
			{
				{0, 		0, 			19, 		0, 			0, 			19, 		0, 			0, 			19, 		0, 			0, 			19, 		0, 			0, 			19 }, 
			},	
		}
	},
	{ //Marathon
		{
			{
				{0.88, 		0.5, 			4, 			0.94, 			0.75, 			4, 			0, 			0, 			3, 			1.13, 			1.25, 			1, 			1.25, 			1.5, 			-1 }, 
				{0.81, 		0.5, 			-1, 			0.87, 			0.75, 			2, 			0, 			0, 			3, 			1.05, 			1.25, 			4,				1.15,			1.5,			 4 },
				{0.88, 		0.5, 			4, 			0.94, 			0.75, 			4, 			0, 			0, 			3, 			1.13, 			1.25, 			1, 			1.25, 			1.5, 			-1 }, 	
				{0.81, 		0.5, 			-1, 			0.87, 			0.75, 			2, 			0, 			0, 			3, 			1.05, 			1.25, 			4,				1.15,			1.5,			 4 },
				{0, 		0, 			-1, 			0, 			0, 			1, 			0, 			0, 			2, 			0, 			0, 			3, 			0, 			0, 			4}, 	
				{0, 		0, 			-1, 			0, 			0, 			1, 			0, 			0, 			2, 			0, 			0, 			3, 			0, 			0, 			4}		
			},
			{
				{0.81, 		0.5, 			5, 			0.87, 			0.75, 			4, 			0, 			0, 			4, 			1.05, 			1.25, 			2,				1.15,			1.5,			 1 },				
				{0.81, 		0.5, 			5, 			0.87, 			0.75, 			4, 			0, 			0, 			4, 			1.05, 			1.25, 			2,				1.15,			1.5,			 1 },	
				{0, 		0, 			-1, 			0, 			0, 			1, 			0, 			0, 			2, 			0, 			0, 			3, 			0, 			0, 			4}, 	
				{0, 		0, 			-1, 			0, 			0, 			1, 			0, 			0, 			2, 			0, 			0, 			3, 			0, 			0, 			4}, 		
				{0.88, 		0.5, 			1, 			0.94, 			0.75, 			1, 			0, 			0, 			2, 			1.13, 			1.25, 			4,				1.25,			1.5,			 4 },				
				{0.88, 		0.5, 			1, 			0.94, 			0.75, 			1, 			0, 			0, 			2, 			1.13, 			1.25, 			4,				1.25,			1.5,			 4 }
			},
			{
				{0.88, 		0.5, 			3, 			0.94, 			0.75, 			2, 			0, 			0, 			4, 			1.13, 			1.25, 			4,				1.25,			1.5,			 1 },	
				{0.88, 		0.5, 			4, 			0.94, 			0.75, 			2, 			0, 			0, 			3, 			1.13, 			1.25, 			2,				1.25,			1.5,			 4 },
				{0.88, 		0.5, 			-1, 			0.94, 			0.75, 			-1, 			0, 			0, 			1, 			1.13, 			1.25, 			2,				1.25,			1.5,			 3 }
			},
			{
				{0.88, 		0.5, 			3, 			0.94, 			0.75, 			2, 			0, 			0, 			4, 			1.13, 			1.25, 			4,				1.25,			1.5,			 2 },	
				{0.88, 		0.5, 			3, 			0.94, 			0.75, 			2, 			0, 			0, 			4, 			1.13, 			1.25, 			4,				1.25,			1.5,			 2 },	
				{0.88, 		0.5, 			-1, 			0.94, 			0.75, 			-1, 			0, 			0, 			1, 			1.13, 			1.25, 			2,				1.25,			1.5,			 4 },	
				{0.88, 		0.5, 			-1, 			0.94, 			0.75, 			-1, 			0, 			0, 			1, 			1.13, 			1.25, 			2,				1.25,			1.5,			 4 }
			},
			{
				{0.88,		0.5,			5,				0.94,			0.75,			5,				0,				0,				5,				1.13,			1.25,			3,				1.25,			1.5,			 1},
				{0.88,		0.5,			2,				0.94,			0.75,			2,				0,				0,				4,				1.13,			1.25,			5,				1.25,			1.5,			 4},
				{0.76,		0.8,			1,				0.95,			0.9,				1,				0,				0,				2,				1.19,			1.2,				2,				1.5,				1.4,			 3},	
				{0.89,		0.7,			-1,			0.96,			0.8,				-1,			0,				0,				1,				1.19,			1.2,				1,				1.32,			1.5,			 1},
				{0.73,		0.5,			3,				0.8,				0.66,			3,				0,				0,				4,				1.13,			1.34,			3,				1.25,			1.5,			 2},
			},	
			{
				{0.88,		0.5,			4,				0.94,			0.75,			4,				0,				0,				4,				1.13,			1.25,			5,				1.25,			1.5,			 4},
				{0,			0,				1,				0,					0,					1,				0,				0,				2,				0,					0,					3,				0,					0,				 3},
				{0,			0,				1,				0,					0,					1,				0,				0,				2,				0,					0,					3,				0,					0,				 3},
				{0.76,		0.8,			1,				0.95,			0.9,				1,				0,				0,				2,				1.19,			1.2,				2,				1.5,				1.4,			 3},	
				{0.89,		0.7,			-1,			0.96,			0.8,				-1,			0,				0,				1,				1.19,			1.2,				1,				1.32,			1.5,			 1},
				{0.73,		0.5,			5,				0.8,				0.66,			5,				0,				0,				2,				1.13,			1.34,			2,				1.25,			1.5,			 1},
			},	
			{
				{0.88,		0.5,			5,				0.94,			0.75,			5,				0,				0,				5,				1.13,			1.25,			5,				1.25,			1.5,			 5},
				{0.88,		0.5,			5,				0.94,			0.75,			5,				0,				0,				5,				1.13,			1.25,			5,				1.25,			1.5,			 5},
			},	
			{
				{0.88,		0.5,			5,				0.94,			0.75,			5,				0,				0,				5,				1.13,			1.25,			5,				1.25,			1.5,			 5},
				{0.88,		0.5,			5,				0.94,			0.75,			5,				0,				0,				5,				1.13,			1.25,			5,				1.25,			1.5,			 5},
				{0.88,		0.5,			1,				0.94,			0.75,			1,				0,				0,				2,				1.13,			1.25,			3,				1.25,			1.5,			 4}
			},	
			{
				{0.88,		0.5,			4,				0.94,			0.75,			4,				0,				0,				3,				1.13,			1.25,			2,				1.25,			1.5,			1},
				{0.88,		0.5,			1,				0.94,			0.75,			2,				0,				0,				3,				1.13,			1.25,			3,				1.25,			1.5,			4},
//				{0.88,		0.5,			1,				0.94,			0.75,			1,				0,				0,				2,				1.13,			1.25,			2,				1.25,			1.5,			3},
			},
			{
				{0.88,		0.5,			4,				0.94,			0.75,			4,				0,				0,				3,				1.13,			1.25,			2,				1.25,			1.5,			1},
				{0.88,		0.5,			1,				0.94,			0.75,			2,				0,				0,				3,				1.13,			1.25,			4,				1.25,			1.5,			5},
				{0.88,		0.5,			1,				0.94,			0.75,			1,				0,				0,				1,				1.13,			1.25,			1,				1.25,			1.5,			2},
			},
			{
				{0.88,		0.5,			3,				0.94,			0.75,			3,				0,				0,				3,				1.13,			1.25,			2,				1.25,			1.5,			1},
				{0,			0,				3,				0,					0,					3,				0,				0,				3,				0,					0,					2,				0,					0,				-1},
				{0,			0,				1,				0,					0,					1,				0,				0,				1,				0,					0,					-1,			0,					0,				-1},
				{0.88,		0.5,			1,				0.94,			0.75,			1,				0,				0,				2,				1.13,			1.25,			3,				1.25,			1.5,			4},
				{0,			0,				-1,			0,					0,					-1,			0,				0,				1,				0,					0,					3,				0,					0,				4},
				{0,			0,				-1,			0,					0,					-1,			0,				0,				-1,			0,					0,					1,				0,					0,				1},
			},
			{
				{0.88,		0.5,			5,				0.94,			0.75,			5,				0,				0,				5,				1.13,			1.25,			3,				1.25,			1.5,			1},
				{0.88,		0.5,			5,				0.94,			0.75,			5,				0,				0,				5,				1.13,			1.25,			3,				1.25,			1.5,			1},
				{0.88,		0.5,			3,				0.94,			0.75,			3,				0,				0,				4,				1.13,			1.25,			3,				1.25,			1.5,			2},
				{0.88,		0.5,			1,				0.94,			0.75,			1,				0,				0,				2,				1.13,			1.25,			4,				1.25,			1.5,			5},
				{0,			0,				-1,			0,					0,					-1,			0,				0,				1,				0,					0,					2,				0,					0,				3},
				{0.88,		0.5,			2,				0.94,			0.75,			2,				0,				0,				3,				1.13,			1.25,			2,				1.25,			1.5,			4},
			},	
			{
				{0.88,		0.5,			4,				0.94,			0.75,			4,				0,				0,				4,				1.13,			1.25,			3,				1.25,			1.5,			3},
				{0,			0,				-1,			0,					0,					-1,			0,				0,				1,				0,					0,					1,				0,					0,				2},
				{0.88,		0.5,			4,				0.94,			0.75,			4,				0,				0,				4,				1.13,			1.25,			3,				1.25,			1.5,			3}
			},
			{
				{0.88,		0.5,			2,				0.94,			0.75,			2,				0,				0,				3,				1.13,			1.25,			1,				1.25,			1.5,			2},
				{0.88,		0.5,			4,				0.94,			0.75,			4,				0,				0,				3,				1.13,			1.25,			2,				1.25,			1.5,			1},
				{0.88,		0.5,			1,				0.94,			0.75,			1,				0,				0,				2,				1.13,			1.25,			1,				1.25,			1.5,			2},
				{0.88,		0.5,			3,				0.94,			0.75,			3,				0,				0,				2,				1.13,			1.25,			4,				1.25,			1.5,			4},
			},	
			{
				{0.88,		0.5,			4,				0.94,			0.75,			4,				0,				0,				3,				1.13,			1.25,			2,				1.25,			1.5,			1},
				{0.88,		0.5,			2,				0.94,			0.75,			2,				0,				0,				2,				1.13,			1.25,			2,				1.25,			1.5,			4},
				{0.73,		0.5,			1,				0.78,			0.75,			1,				0,				0,				1,				1.13,			1.25,			2,				1.25,			1.5,			3},
			},
			{
				{0.88,		0.5,			1,				0.94,			0.75,			1,				0,				0,				1,				1.13,			1.25,			2,				1.25,			1.5,			3},
				{0.88,		0.5,			3,				0.94,			0.75,			3,				0,				0,				2,				1.13,			1.25,			2,				1.25,			1.5,			1},
			},
			{
				{0.88,		0.5,			2,				0.94,			0.75,			2,				0,				0,				2,				1.13,			1.25,			2,				1.25,			1.5,			2},
			},
		}	
	},	
	{
		{	
			{
				{0,			0,				3,				0,					0,					3,				0,				0,				3,				0,					0,					4,				0,					0,				4},
				{0,			0,				2,				0,					0,					2,				0,				0,				1,				1.25,			0,					1,				2.0,				0,				1}
			},
			{},
			{},
			{},
			{
				{0,			0,				5,				0,					0,					5,				0,				0,				4,				1.25,			0,					4,				2.0,				0,				3},
				{0,			0,				1,				0,					0,					1,				0,				0,				1,				1.25,			0,					2,				2.0,				0,				2},
				{0,			0,				2,				0,					0,					2,				0,				0,				2,				1.25,			0,					1,				2.0,				0,				1}
			},
			{
				{0,			0,				5,				0,					0,					5,				0,				0,				4,				0,					0,					4,				0,					0,				4},
				{0,			0,				1,				0,					0,					1,				0,				0,				1,				0,					0,					2,				0,					0,				3},
				{0,			0,				1,				0,					0,					1,				0,				0,				1,				0,					0,					2,				0,					0,				3},
				{0,			0,				1,				0,					0,					1,				0,				0,				1,				0,					0,					2,				0,					0,				3}
			},
			{
				{0,			0,				3,				0,					0,					3,				0,				0,				3,				0,					0,					2,				0,					0,				2},
				{0,			0,				1,				0,					0,					1,				0,				0,				2,				0,					0,					2,				0,					0,				3}
			},
			{
				{0,			0,				2,				0,					0,					2,				0,				0,				2,				0,					0,					2,				0,					0,				2},
				{0,			0,				2,				0,					0,					2,				0,				0,				2,				0,					0,					2,				0,					0,				2},
				{0,			0,				2,				0,					0,					2,				0,				0,				2,				0,					0,					2,				0,					0,				2},
				{0,			0,				1,				0,					0,					1,				0,				0,				1,				0,					0,					1,				0,					0,				1},
			},
			{},
			{
				{0,			0,				4,				0,					0,					4,				0,				0,				3,				0,					0,					4,				0,					0,				2},
				{0,			0,				1,				0,					0,					1,				0,				0,				1,				0,					0,					2,				0,					0,				2}
			},
			{},
			{},
			{},
			{
				{0,			0,				3,				0,					0,					5,				0,				0,				3,				0,					0,					2,				0,					0,				-1},
				{0,			0,				-1,			0,					0,					1,				0,				0,				1,				0,					0,					3,				0,					0,				 3}
			},
			{},
			{
				{0,			0,				2,				0,					0,					2,				0,				0,				2,				0,					0,					2,				0,					0,				3},
				{0,			0,				1,				0,					0,					1,				0,				0,				2,				0,					0,					2,				0,					0,				2}
			},
			{
				{0,			0,				1,				0,					0,					1,				0,				0,				2,				0,					0,					3,				0,					0,				4},
				{0,			0,				2,				0,					0,					2,				0,				0,				2,				0,					0,					2,				0,					0,				1}
			},
			{},
		}
	},	
	{ //RoTT
		{
			{	
				{0,			0.75,		1,				0,					0,					1,				0,				1.25,		1,				0,					1.5,				1,				0,					1.75,		1},
			},
			{
				{0,			0.9,			5,				0,					0,					5,				0,				1.2,			5,				0,					1.5,				5,				0,					1.8,			1},
				{0,			0.9,			1,				0,					0,					2,				0,				1.2,			3,				0,					1.5,				4,				0,					1.8,			1},
			},
			{
				{0,			0.75,		1,				0,					0,					1,				0,				1.25,		1,				0,					1.5,				1,				0,					1.75,		1},
			},
			{
				{0,			0.7,			5,				0,					0,					5,				0,				1.3,			5,				0,					1.6,				5,				0,					2.0,			1},
			},
			{
				{0,			0.8,			5,				0,					0,					5,				0,				1.1,			5,				0,					1.2,				5,				0,					1.4,			5}
			},
			{
				{0,			0.8,			5,				0,					0,					5,				0,				1.1,			5,				0,					1.2,				5,				0,					1.4,			5}
			},
			{
				{0,			0.8,			5,				0,					0,					5,				0,				1.2,			5,				0,					1.4,				5,				0,					1.6,			5}
			},	
			{
				{0,			0.65,		1,				0,					0,					1,				0,				1.05,		3,				0,					1.22,			3,				0,					1.44,		3}
			},
			{
				{0,			0.8,			5,				0,					0,					5,				0,				1.2,			5,				0,					1.4,				5,				0,					1.6,			5}
			},
			{
				{0,			0.8,			5,				0,					0,					5,				0,				1.2,			5,				0,					1.4,				5,				0,					1.6,			5}
			},
			{
				{0,			0.5,			5,				0,					0,					5,				0,				1.5,			5,				0,					2.0,				5,				0,					5.0,			5}
			},
			{
				{0,			0.8,			5,				0,					0,					5,				0,				1.2,			5,				0,					1.4,				5,				0,					1.6,			5}
			},
			{
				{0,			0.8,			5,				0,					0,					5,				0,				1.2,			5,				0,					1.4,				5,				0,					1.6,			5}
			},
			{
				{0,			0.9,			3,				0,					0,					3,				0,				1.09,		3,				0,					1.27,			3,				0,					2.0,			3},
				{0,			0.8,			4,				0,					0,					4,				0,				1.2,			3,				0,					1.4,				2,				0,					2.0,			1}
			},
			{
				{0,			0.9,			5,				0,					0,					5,				0,				1.1,			5,				0,					1.1,				5,				0,					1.4,			5}
			},
			{
				{0,			0,				2,				0,					1.5,				3,				0,				1.67,		2,				0,					2.0,				3,				0,					2.25,		3},
				{0,			0,				-1,			0,					1.2,				1,				0,				1.5,			1,				0,					1.6,				2,				0,					1.8,			3}
			},
			{
				{0,			0.8,			2,				0,					0,					3,				0,				1.25,		4,				0,					1.5,				5,				0,					1.6,			5},
				{0,			0,				4,				0,					1.4,				4,				0,				1.45,		4,				0,					1.55,			4,				0,					1.8,			3}
			},
			{},
		}
	},	
	{//Blake Stone
		{
			{
				{0, 			0.4,			2,				0,					0.6,				2,				0,				0,				2,				0,					1.2,				2,				0,					1.4,			2},
				{0,			0.4,			2,				0,					0.6,				2,				0,				0,				2,				0,					1.25,			2,				0,					1.5,			2},
				{0,			0.4,			2,				0,					0.6,				2,				0,				0,				2,				0,					1.25,			2,				0,					1.5,			2}
			},
			{
				{0,			0.4,			2,				0,					0.6,				2,				0,				0,				2,				0,					1.25,			3,				0,					1.5,			2},
				{0,			0.4,			2,				0,					0.6,				2,				0,				0,				2,				0,					1.25,			3,				0,					1.5,			2},
				{0,			0.4,			1,				0,					0.6,				1,				0,				0,				1,				0,					1.2,				1,				0,					1.5,			1}
			},
			{
				{0,			0.4,			5,				0,					0.6,				5,				0,				0,				5,				0,					1.33,			5,				0,					1.5,			5}
			},
			{
				{0,			0.4,			5,				0,					0.6,				5,				0,				0,				5,				0,					1.166,			5,				0,					1.4,			5},
				{0,			0.4,			5,				0,					0.6,				5,				0,				0,				5,				0,					1.166,			5,				0,					1.4,			5}
			},
			{
				{0,			0.4,			5,				0,					0.6,				5,				0,				0,				5,				0,					1.2,				5,				0,					1.4,			5},
			},
			{
				{0,			0.4,			5,				0,					0.6,				5,				0,				0,				5,				0,					1.25,			5,				0,					1.5,			5},
			},
			{
				{0,			0.5,			5,				0,					0.7,				5,				0,				0,				5,				0,					1.3,				5,				0,					1.5,			5},
				{0,			0.5,			2,				0,					0.75, 			3,				0,				0,				3,				0,					1.25,			3,				0,					1.5,			4},
				{0,			0.5,			5,				0,					0.75,			4,				0,				0,				4,				0,					1.25,			3,				0,					1.5,			3}
			},
			{
				{0,			0.5,			5,				0,					0.75,			5,				0,				0,				5,				0,					1.25,			5,				0,					1.5,			5},
				{0,			0.5,			5,				0,					0.75,			5,				0,				0,				5,				0,					1.25,			5,				0,					1.5,			5}
			},
			{
				{0,			0.6,		    5,				0,					0.75,			5,				0,				0,				5,				0,					1.25,			5,				0,					1.5,			5},
			},
			{
				{0,			0.5,			5,				0,					0.75,			5,				0,				0,				5,				0,					1.25,			5,				0,					1.5,			5},
				{0,			0.4,			3,				0,					0.6,				3,				0,				0,				3,				0,					1.2,				3,				0,					1.4,			4}
			},
			{
				{0,			0.5,			4,				0,					0.75,			4,				0,				0,				4,				0,					1.25,			4,				0,					1.5,			4},
				{0.75,		0,				3,				0,					0.9,				3,				0,				0,				3,				0,					1.2,				3,				0,					1.4,			3}
			},	
			{
				{0,			0.6,			5,				1.2,				0.8,				5,				1.4,			0,				5,				1.6,				1.2,				5,				1.75,			1.5,			5}
			},
			{
				{0,			0.6,			5,				1.2,				0.8,				5,				1.4,			0,				5,				1.6,				1.2,				5,				1.75,			1.5,			5}
			},
			{
				{0,			0.4,			4,				0,					0.6,				4,				0,				0,				4,				0,					1.2,				4,				0,					1.5,			4},
				{0,			0.6,			3,				0,					0.9,				3,				0,				0,				3,				0,					1.2,				3,				0,					1.4,			3},
				{0,			0.4,			2,				0,					0.6,				2,				0,				0,				2,				0,					1.31,			2,				0,					1.6,			2},
				{0,			0.4,			2,				0,					0.6,				2,				0,				0,				2,				0,					1.31,			2,				0,					1.6,			2}
			},
			{
				{0,			0.4,			3,				0,					0.8,				3,				0,				0,				3,				0,					1.2,				3,				0,					1.4,			3},
				{0,			0.5,			4,				0,					0.75,			4,				0,				0,				4,				0,					1.33,			4,				0,					1.66,		4}
			},
			{
				{0,			0.5,			4,				0,					0.66,			4,				0,				0,				4,				0,					1.2,				4,				0,					1.5,			4},
				{0,			0.5,			4,				0,					0.75,			4,				0,				0,				4,				0,					1.25,			4,				0,					1.4,			4},
				{0,			0.5,			4,				0,					0.75,			4,				0,				0,				4,				0,					1.25,			4,				0,					1.5,			4},
				{0,			0.5,			2,				0,					0.75,			2,				0,				0,				2,				0,					1.25,			2,				0,					1.4,			2}
			},	
			{
				{0,			0,				5,				0,					0,					5,				0,				0,				5,				0,					1.66,			5,				0,					2.0,			5}
			},
			{
				{0, 			0.4,			2,				0,					0.6,				2,				0,				0,				2,				0,					1.2,				2,				0,					1.4,			2}
			}
		},
	},
	
	{	// Blood
		{
			{
				{0,			0,				2,				0,					1.5,				2,				0,				2.0,			2,				0,					2.5,				2,				0,					3.1,			2}
			},
			{
				{0,			0,				2,				0,					1.5,				2,				0,				2.0,			2,				0,					2.5,				2,				0,					3.1,			2}
			},
			{
				{0,			0,				3,				0,					1.4,				3,				0,				2.0,			3,				0,					2.6,				3,				0,					3.4,			3}
			},
			{
				{0,			0,				2,				0,					1.5,				2,				0,				2.0,			2,				0,					2.5,				2,				0,					3.1,			2}
			},
			{
				{0,			0,				3,				0,					1.32,			3,				0,				1.91,		3, 			0,					2.5,				3,				0,					3.23,		3},
				{0,			0,				3,				0,					1.41,			3,				0,				2.17,		3,				0,					2.65,			3,				0,					3.37,		3}
			},
			{
				{0,			0,				3,				0,					1.75,			3,				0,				2.5,			3,				0,					3.5,				3,				0,					4.5,			3},
			},
			{
				{0,			0,				3,				0,					1.41,			3,				0,				2.0,			3,				0,					2.76,			3,				0,					3.4,			3}
			},
			{
				{0,			0,				3,				0,					1.2,				3,				0,				1.5,			3,				0,					1.7,				3,				0,					2.0,			3}
			},
			{
				{0, 			0,				3,				0,					1.4,				3,				0,				2.0,			3,				0,					2.6,				3,				0,					3.4,			3},	
			},
			{
				{0,			0,				3,				0,					1.78,			3,				0,				2.22,		3,				0,					3.11,			3,				0,					3.55,		3}
			},
			{
				{0,			0,				3,				0,					1.5,				3,				0,				2.0,			3,				0,					3.5,				3,				0,					5.0,			3}
			},
			{
				{0,			0,				3,				0,					1.35,			3,				0,				2.04,		3,				0,					2.63,			3,				0,					3.37,		3}
			},
			{
				{0,			0,				3,				0,					1.3,				3,				0,				1.5,			3,				0,					2.3,				3,				0,					3.2,			3}
			},
			{
				{0,			0,				3,				0,					1.35,			3,				0,				2.0,			3,				0,					2.7,				3,				0,					3.0,			3}
			},
			{
				{0, 			0,				3,				0,					1.4,				3,				0,				2.0,			3,				0,					2.6,				3,				0,					3.4,			3},	
			},
			{
				{0,			0,				3,				0,					1.2,				3,				0,				2.0,			3,				0,					2.4,				3,				0,					3.2,			3},
				{0,			0,				3,				0,					1.25,			3,				0,				2.35,		3,				0,					2.4,				3,				0,					3.5,			3}
			},	
			{
				{0,			0,				3,				0,					1.2,				3,				0,				1.5,			3,				0,					2.0,				3,				0,					3.2,			3}
			},	
			{
				{0,			0,				2,				0,					1.5,				2,				0,				2.0,			2,				0,					2.5,				2,				0,					3.1,			2}
			},	
		},
	},
	{  //Strife
		{
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{
				{0,			0,				5,				0,					0,					4,				0,				0,				3,				0,					0,				2,					0,						0,				1},
				{0,			0,				1,				0,					0,					2,				0,				0,				3,				0,					0,				4,					0,						0,				5}
			},
			{},
			{},
			{},
			{
				{0,			0,				1,				0,					0,					2,				0,				0,				3,				0,					0,				4,					0,						0,				5},
				{0,			0,				5,				0,					0,					4,				0,				0,				3,				0,					0,				2,					0,						0,				1}
			},
			{},
			{},
		}
	},	
	{	// Eradicator
		{
			{},
			{},
			{},
			{},
			{
				{0.66,			0,			5,				0.75,			0,			5,				0,				0,			5,			1.25,			0,			5,			1.5,		0,			5},
			},
			{
				{0.66,			0,			5,				0.75,			0,			5,				0,				0,			5,			1.25,			0,			5,			1.5,		0,			5},
			},
			{},
			{},
			{},
			{},
			{
				{0.8,			0,			4,				0.9,				0,			4,				1.25,		0,			4,			1.5,			0,			4,			2.0,			0,			4},
				{0.8,			0,			1,				0.9,				0,			1,				1.25,		0,			1,			1.5,			0,			1,			2.0,			0,			1},
				{0,			0,			3,				0,					0,			3,				0,				0,			3,			0,				0,			3,			0,				0,			3}
			},
			{},
			{},
		}
	},	
	{ // Corridor 7
		{ 
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{},
			{
				{0,		0,			5,			0,				0,				5,				0,			0,				5,				0,			0,		5,			0,				0,			5},
				{0,		0,			3,			0,				0,				3,				0,			0,				3,				0,			0,		3,			0,				0,			3}
			},	
			{},
			{},					
		}
	},
};